<?php

/**
 * Register blocks using metadata collections for improved performance.
 * Supports multiple locations and provides backward compatibility.
 */
add_action( 'init', function () {
    
    /**
     * Define the block locations. 
     * Filter allows third-party developers or child themes to add their own block directories.
     */
    $blocks_locations = apply_filters( 'farmacia_della_bona_blocks_locations', [
        __DIR__ . '/build/blocks',
    ] );

    if ( ! is_array( $blocks_locations ) ) {
        return;
    }

    foreach ( $blocks_locations as $dir ) {
        // Clean path to avoid double slashes issues.
        $dir = untrailingslashit( $dir );

        // Path to the manifest file generated by the build process.
        $manifest = $dir . '/blocks-manifest.php';

        // Skip this location if the manifest file is missing.
        if ( ! file_exists( $manifest ) ) {
            continue;
        }
    
        /**
         * WP 6.8+: Modern approach. 
         * Registers the block(s) metadata from the `blocks-manifest.php` and registers the block type(s)
         * based on the registered block metadata. Behind the scenes, it registers also all assets so they can be enqueued
         * through the block editor in the corresponding context.
         *
         * @see https://make.wordpress.org/core/2025/03/13/more-efficient-block-type-registration-in-6-8/
         * @see https://make.wordpress.org/core/2024/10/17/new-block-type-registration-apis-to-improve-performance-in-wordpress-6-7/
         */
        if ( function_exists( 'wp_register_block_types_from_metadata_collection' ) ) {
            wp_register_block_types_from_metadata_collection( $dir, $manifest );
            continue;
        }

        /**
         * WP 6.1 - 6.7: Optimization.
         * Indexes the collection to improve performance during manual registration.
         */
        if ( function_exists( 'wp_register_block_metadata_collection' ) ) {
            wp_register_block_metadata_collection( $dir, $manifest );
        }

        /**
         * WP 5.5-6.7 Fallback: Manual registration.
         * Just loop the manifest directly through the manifest keys and registers each block from metadata.
         */
        if ( function_exists( 'register_block_type_from_metadata' ) ) {
            $manifest_data = include $manifest;
            if ( is_array( $manifest_data ) ) {
                foreach ( array_keys( $manifest_data ) as $block_type ) {
                    register_block_type_from_metadata( $dir . '/' . $block_type );
                }
            }  
        }
    }

} );
 